### ISSUE TITLE
undefined: gocui.Quit undefined: gocui.ModNone

### ISSUE THREAD

**Issue by owllie90** [SumoLogic/sumoshell#12] opened 2016-12-21 09:29 UTC
i am doing the go get ./... for the installation of sumoshell

But i am encountering the below error:

undefined: gocui.Quit
undefined: gocui.ModNone

Kindly advise

Thanks.

**Comment by rcoh** [comment] 2016-12-21 13:58
It's caused by a dependency that was upgraded. I have a branch with a fix,
will push soon.

**Comment by owllie90** [comment] 2016-12-22 00:38
hi, any estimate when? 

Thanks :)

**Comment by rcoh** [comment] 2016-12-22 15:34
https://github.com/SumoLogic/sumoshell/pull/13

**Comment by rcoh** [comment] 2016-12-22 21:00
Merged. I have a few more improvements on my list that should come out soon

**Closed as completed** 2016-12-22 21:00 UTC
